package com.chun.quartz.dao;

import com.chun.quartz.model.ContractDetail;
import java.util.List;

public interface ContractDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_detail
     *
     * @mbg.generated
     */
    int insert(ContractDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_detail
     *
     * @mbg.generated
     */
    ContractDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_detail
     *
     * @mbg.generated
     */
    List<ContractDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContractDetail record);
}