package com.chun.quartz.dao;

import com.chun.quartz.model.EmMonitorVehicle;
import java.util.List;

public interface EmMonitorVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_monitor_vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_monitor_vehicle
     *
     * @mbg.generated
     */
    int insert(EmMonitorVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_monitor_vehicle
     *
     * @mbg.generated
     */
    EmMonitorVehicle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_monitor_vehicle
     *
     * @mbg.generated
     */
    List<EmMonitorVehicle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_monitor_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmMonitorVehicle record);
}