package com.chun.quartz.dao;

import com.chun.quartz.model.EmVehicle;
import java.util.List;

public interface EmVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_vehicle
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_vehicle
     *
     * @mbg.generated
     */
    int insert(EmVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_vehicle
     *
     * @mbg.generated
     */
    EmVehicle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_vehicle
     *
     * @mbg.generated
     */
    List<EmVehicle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_vehicle
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmVehicle record);
}