package com.chun.quartz.dao;

import com.chun.quartz.model.FltSpot;
import java.util.List;

public interface FltSpotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flt_spot
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flt_spot
     *
     * @mbg.generated
     */
    int insert(FltSpot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flt_spot
     *
     * @mbg.generated
     */
    FltSpot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flt_spot
     *
     * @mbg.generated
     */
    List<FltSpot> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flt_spot
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FltSpot record);
}