package com.chun.quartz.dao;

import com.chun.quartz.model.Migrations;
import java.util.List;

public interface MigrationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migrations
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migrations
     *
     * @mbg.generated
     */
    int insert(Migrations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migrations
     *
     * @mbg.generated
     */
    Migrations selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migrations
     *
     * @mbg.generated
     */
    List<Migrations> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table migrations
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Migrations record);
}