package com.chun.quartz.dao;

import com.chun.quartz.model.QrtzPausedTriggerGrps;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzPausedTriggerGrpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbg.generated
     */
    int insert(QrtzPausedTriggerGrps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_paused_trigger_grps
     *
     * @mbg.generated
     */
    List<QrtzPausedTriggerGrps> selectAll();
}