package com.chun.quartz.dao;

import com.chun.quartz.model.QrtzCalendars;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzCalendarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("calendarName") String calendarName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbg.generated
     */
    int insert(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbg.generated
     */
    QrtzCalendars selectByPrimaryKey(@Param("schedName") String schedName, @Param("calendarName") String calendarName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbg.generated
     */
    List<QrtzCalendars> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QrtzCalendars record);
}