package com.chun.quartz.dao;

import com.chun.quartz.model.QrtzCronTriggers;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzCronTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbg.generated
     */
    int insert(QrtzCronTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbg.generated
     */
    QrtzCronTriggers selectByPrimaryKey(@Param("schedName") String schedName, @Param("triggerName") String triggerName, @Param("triggerGroup") String triggerGroup);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbg.generated
     */
    List<QrtzCronTriggers> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_cron_triggers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QrtzCronTriggers record);
}