package com.chun.quartz.model;

import java.io.Serializable;
import java.util.Date;

public class Contract implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.carrier
     *
     * @mbg.generated
     */
    private String carrier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.ac_type
     *
     * @mbg.generated
     */
    private String acType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.contract_number
     *
     * @mbg.generated
     */
    private String contractNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.party_a
     *
     * @mbg.generated
     */
    private String partyA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.party_b
     *
     * @mbg.generated
     */
    private String partyB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.party_a_user
     *
     * @mbg.generated
     */
    private String partyAUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.party_b_user
     *
     * @mbg.generated
     */
    private String partyBUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contract
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.id
     *
     * @return the value of contract.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.id
     *
     * @param id the value for contract.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.carrier
     *
     * @return the value of contract.carrier
     *
     * @mbg.generated
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.carrier
     *
     * @param carrier the value for contract.carrier
     *
     * @mbg.generated
     */
    public void setCarrier(String carrier) {
        this.carrier = carrier == null ? null : carrier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.ac_type
     *
     * @return the value of contract.ac_type
     *
     * @mbg.generated
     */
    public String getAcType() {
        return acType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.ac_type
     *
     * @param acType the value for contract.ac_type
     *
     * @mbg.generated
     */
    public void setAcType(String acType) {
        this.acType = acType == null ? null : acType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.create_time
     *
     * @return the value of contract.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.create_time
     *
     * @param createTime the value for contract.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.update_time
     *
     * @return the value of contract.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.update_time
     *
     * @param updateTime the value for contract.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.contract_number
     *
     * @return the value of contract.contract_number
     *
     * @mbg.generated
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.contract_number
     *
     * @param contractNumber the value for contract.contract_number
     *
     * @mbg.generated
     */
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber == null ? null : contractNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.party_a
     *
     * @return the value of contract.party_a
     *
     * @mbg.generated
     */
    public String getPartyA() {
        return partyA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.party_a
     *
     * @param partyA the value for contract.party_a
     *
     * @mbg.generated
     */
    public void setPartyA(String partyA) {
        this.partyA = partyA == null ? null : partyA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.party_b
     *
     * @return the value of contract.party_b
     *
     * @mbg.generated
     */
    public String getPartyB() {
        return partyB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.party_b
     *
     * @param partyB the value for contract.party_b
     *
     * @mbg.generated
     */
    public void setPartyB(String partyB) {
        this.partyB = partyB == null ? null : partyB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.party_a_user
     *
     * @return the value of contract.party_a_user
     *
     * @mbg.generated
     */
    public String getPartyAUser() {
        return partyAUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.party_a_user
     *
     * @param partyAUser the value for contract.party_a_user
     *
     * @mbg.generated
     */
    public void setPartyAUser(String partyAUser) {
        this.partyAUser = partyAUser == null ? null : partyAUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.party_b_user
     *
     * @return the value of contract.party_b_user
     *
     * @mbg.generated
     */
    public String getPartyBUser() {
        return partyBUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.party_b_user
     *
     * @param partyBUser the value for contract.party_b_user
     *
     * @mbg.generated
     */
    public void setPartyBUser(String partyBUser) {
        this.partyBUser = partyBUser == null ? null : partyBUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.start_time
     *
     * @return the value of contract.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.start_time
     *
     * @param startTime the value for contract.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.end_time
     *
     * @return the value of contract.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.end_time
     *
     * @param endTime the value for contract.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contract.img
     *
     * @return the value of contract.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contract.img
     *
     * @param img the value for contract.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", carrier=").append(carrier);
        sb.append(", acType=").append(acType);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", contractNumber=").append(contractNumber);
        sb.append(", partyA=").append(partyA);
        sb.append(", partyB=").append(partyB);
        sb.append(", partyAUser=").append(partyAUser);
        sb.append(", partyBUser=").append(partyBUser);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", img=").append(img);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}