package com.chun.quartz.model;

import java.io.Serializable;
import java.util.Date;

public class EmVehicle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.no
     *
     * @mbg.generated
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.brand_no
     *
     * @mbg.generated
     */
    private String brandNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.frame_no
     *
     * @mbg.generated
     */
    private String frameNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.engine_no
     *
     * @mbg.generated
     */
    private String engineNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.fuel_consumption
     *
     * @mbg.generated
     */
    private Float fuelConsumption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.total_weight
     *
     * @mbg.generated
     */
    private Float totalWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.approved_passenger
     *
     * @mbg.generated
     */
    private Integer approvedPassenger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.purchase_date
     *
     * @mbg.generated
     */
    private Date purchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.maintenance_date
     *
     * @mbg.generated
     */
    private Date maintenanceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.annual_review_date
     *
     * @mbg.generated
     */
    private Date annualReviewDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.scrap_date
     *
     * @mbg.generated
     */
    private Date scrapDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.scrap_status
     *
     * @mbg.generated
     */
    private String scrapStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.insurance_date
     *
     * @mbg.generated
     */
    private Date insuranceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_vehicle.sim_no
     *
     * @mbg.generated
     */
    private String simNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table em_vehicle
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.id
     *
     * @return the value of em_vehicle.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.id
     *
     * @param id the value for em_vehicle.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.no
     *
     * @return the value of em_vehicle.no
     *
     * @mbg.generated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.no
     *
     * @param no the value for em_vehicle.no
     *
     * @mbg.generated
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.brand_no
     *
     * @return the value of em_vehicle.brand_no
     *
     * @mbg.generated
     */
    public String getBrandNo() {
        return brandNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.brand_no
     *
     * @param brandNo the value for em_vehicle.brand_no
     *
     * @mbg.generated
     */
    public void setBrandNo(String brandNo) {
        this.brandNo = brandNo == null ? null : brandNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.color
     *
     * @return the value of em_vehicle.color
     *
     * @mbg.generated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.color
     *
     * @param color the value for em_vehicle.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.type
     *
     * @return the value of em_vehicle.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.type
     *
     * @param type the value for em_vehicle.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.frame_no
     *
     * @return the value of em_vehicle.frame_no
     *
     * @mbg.generated
     */
    public String getFrameNo() {
        return frameNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.frame_no
     *
     * @param frameNo the value for em_vehicle.frame_no
     *
     * @mbg.generated
     */
    public void setFrameNo(String frameNo) {
        this.frameNo = frameNo == null ? null : frameNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.engine_no
     *
     * @return the value of em_vehicle.engine_no
     *
     * @mbg.generated
     */
    public String getEngineNo() {
        return engineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.engine_no
     *
     * @param engineNo the value for em_vehicle.engine_no
     *
     * @mbg.generated
     */
    public void setEngineNo(String engineNo) {
        this.engineNo = engineNo == null ? null : engineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.fuel_consumption
     *
     * @return the value of em_vehicle.fuel_consumption
     *
     * @mbg.generated
     */
    public Float getFuelConsumption() {
        return fuelConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.fuel_consumption
     *
     * @param fuelConsumption the value for em_vehicle.fuel_consumption
     *
     * @mbg.generated
     */
    public void setFuelConsumption(Float fuelConsumption) {
        this.fuelConsumption = fuelConsumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.total_weight
     *
     * @return the value of em_vehicle.total_weight
     *
     * @mbg.generated
     */
    public Float getTotalWeight() {
        return totalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.total_weight
     *
     * @param totalWeight the value for em_vehicle.total_weight
     *
     * @mbg.generated
     */
    public void setTotalWeight(Float totalWeight) {
        this.totalWeight = totalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.approved_passenger
     *
     * @return the value of em_vehicle.approved_passenger
     *
     * @mbg.generated
     */
    public Integer getApprovedPassenger() {
        return approvedPassenger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.approved_passenger
     *
     * @param approvedPassenger the value for em_vehicle.approved_passenger
     *
     * @mbg.generated
     */
    public void setApprovedPassenger(Integer approvedPassenger) {
        this.approvedPassenger = approvedPassenger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.purchase_date
     *
     * @return the value of em_vehicle.purchase_date
     *
     * @mbg.generated
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.purchase_date
     *
     * @param purchaseDate the value for em_vehicle.purchase_date
     *
     * @mbg.generated
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.maintenance_date
     *
     * @return the value of em_vehicle.maintenance_date
     *
     * @mbg.generated
     */
    public Date getMaintenanceDate() {
        return maintenanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.maintenance_date
     *
     * @param maintenanceDate the value for em_vehicle.maintenance_date
     *
     * @mbg.generated
     */
    public void setMaintenanceDate(Date maintenanceDate) {
        this.maintenanceDate = maintenanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.annual_review_date
     *
     * @return the value of em_vehicle.annual_review_date
     *
     * @mbg.generated
     */
    public Date getAnnualReviewDate() {
        return annualReviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.annual_review_date
     *
     * @param annualReviewDate the value for em_vehicle.annual_review_date
     *
     * @mbg.generated
     */
    public void setAnnualReviewDate(Date annualReviewDate) {
        this.annualReviewDate = annualReviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.scrap_date
     *
     * @return the value of em_vehicle.scrap_date
     *
     * @mbg.generated
     */
    public Date getScrapDate() {
        return scrapDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.scrap_date
     *
     * @param scrapDate the value for em_vehicle.scrap_date
     *
     * @mbg.generated
     */
    public void setScrapDate(Date scrapDate) {
        this.scrapDate = scrapDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.scrap_status
     *
     * @return the value of em_vehicle.scrap_status
     *
     * @mbg.generated
     */
    public String getScrapStatus() {
        return scrapStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.scrap_status
     *
     * @param scrapStatus the value for em_vehicle.scrap_status
     *
     * @mbg.generated
     */
    public void setScrapStatus(String scrapStatus) {
        this.scrapStatus = scrapStatus == null ? null : scrapStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.insurance_date
     *
     * @return the value of em_vehicle.insurance_date
     *
     * @mbg.generated
     */
    public Date getInsuranceDate() {
        return insuranceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.insurance_date
     *
     * @param insuranceDate the value for em_vehicle.insurance_date
     *
     * @mbg.generated
     */
    public void setInsuranceDate(Date insuranceDate) {
        this.insuranceDate = insuranceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.photo
     *
     * @return the value of em_vehicle.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.photo
     *
     * @param photo the value for em_vehicle.photo
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.create_time
     *
     * @return the value of em_vehicle.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.create_time
     *
     * @param createTime the value for em_vehicle.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.update_time
     *
     * @return the value of em_vehicle.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.update_time
     *
     * @param updateTime the value for em_vehicle.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.user_id
     *
     * @return the value of em_vehicle.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.user_id
     *
     * @param userId the value for em_vehicle.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.del_flag
     *
     * @return the value of em_vehicle.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.del_flag
     *
     * @param delFlag the value for em_vehicle.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_vehicle.sim_no
     *
     * @return the value of em_vehicle.sim_no
     *
     * @mbg.generated
     */
    public String getSimNo() {
        return simNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_vehicle.sim_no
     *
     * @param simNo the value for em_vehicle.sim_no
     *
     * @mbg.generated
     */
    public void setSimNo(String simNo) {
        this.simNo = simNo == null ? null : simNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_vehicle
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", no=").append(no);
        sb.append(", brandNo=").append(brandNo);
        sb.append(", color=").append(color);
        sb.append(", type=").append(type);
        sb.append(", frameNo=").append(frameNo);
        sb.append(", engineNo=").append(engineNo);
        sb.append(", fuelConsumption=").append(fuelConsumption);
        sb.append(", totalWeight=").append(totalWeight);
        sb.append(", approvedPassenger=").append(approvedPassenger);
        sb.append(", purchaseDate=").append(purchaseDate);
        sb.append(", maintenanceDate=").append(maintenanceDate);
        sb.append(", annualReviewDate=").append(annualReviewDate);
        sb.append(", scrapDate=").append(scrapDate);
        sb.append(", scrapStatus=").append(scrapStatus);
        sb.append(", insuranceDate=").append(insuranceDate);
        sb.append(", photo=").append(photo);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", userId=").append(userId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", simNo=").append(simNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}