package com.chun.quartz.model;

import java.io.Serializable;
import java.util.Date;

public class FltSpotCopy1 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.spot_number
     *
     * @mbg.generated
     */
    private String spotNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.flight_id
     *
     * @mbg.generated
     */
    private Integer flightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.x
     *
     * @mbg.generated
     */
    private Double x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.y
     *
     * @mbg.generated
     */
    private Double y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.longitude
     *
     * @mbg.generated
     */
    private Double longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.latitude
     *
     * @mbg.generated
     */
    private Double latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.angle
     *
     * @mbg.generated
     */
    private Integer angle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flt_spot_copy1.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table flt_spot_copy1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.id
     *
     * @return the value of flt_spot_copy1.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.id
     *
     * @param id the value for flt_spot_copy1.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.spot_number
     *
     * @return the value of flt_spot_copy1.spot_number
     *
     * @mbg.generated
     */
    public String getSpotNumber() {
        return spotNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.spot_number
     *
     * @param spotNumber the value for flt_spot_copy1.spot_number
     *
     * @mbg.generated
     */
    public void setSpotNumber(String spotNumber) {
        this.spotNumber = spotNumber == null ? null : spotNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.flight_id
     *
     * @return the value of flt_spot_copy1.flight_id
     *
     * @mbg.generated
     */
    public Integer getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.flight_id
     *
     * @param flightId the value for flt_spot_copy1.flight_id
     *
     * @mbg.generated
     */
    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.state
     *
     * @return the value of flt_spot_copy1.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.state
     *
     * @param state the value for flt_spot_copy1.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.x
     *
     * @return the value of flt_spot_copy1.x
     *
     * @mbg.generated
     */
    public Double getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.x
     *
     * @param x the value for flt_spot_copy1.x
     *
     * @mbg.generated
     */
    public void setX(Double x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.y
     *
     * @return the value of flt_spot_copy1.y
     *
     * @mbg.generated
     */
    public Double getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.y
     *
     * @param y the value for flt_spot_copy1.y
     *
     * @mbg.generated
     */
    public void setY(Double y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.longitude
     *
     * @return the value of flt_spot_copy1.longitude
     *
     * @mbg.generated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.longitude
     *
     * @param longitude the value for flt_spot_copy1.longitude
     *
     * @mbg.generated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.latitude
     *
     * @return the value of flt_spot_copy1.latitude
     *
     * @mbg.generated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.latitude
     *
     * @param latitude the value for flt_spot_copy1.latitude
     *
     * @mbg.generated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.angle
     *
     * @return the value of flt_spot_copy1.angle
     *
     * @mbg.generated
     */
    public Integer getAngle() {
        return angle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.angle
     *
     * @param angle the value for flt_spot_copy1.angle
     *
     * @mbg.generated
     */
    public void setAngle(Integer angle) {
        this.angle = angle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.create_time
     *
     * @return the value of flt_spot_copy1.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.create_time
     *
     * @param createTime the value for flt_spot_copy1.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flt_spot_copy1.update_time
     *
     * @return the value of flt_spot_copy1.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flt_spot_copy1.update_time
     *
     * @param updateTime the value for flt_spot_copy1.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flt_spot_copy1
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", spotNumber=").append(spotNumber);
        sb.append(", flightId=").append(flightId);
        sb.append(", state=").append(state);
        sb.append(", x=").append(x);
        sb.append(", y=").append(y);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", angle=").append(angle);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}