package com.chun.quartz.model;

import java.io.Serializable;
import java.util.Date;

public class OperationLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.flight_type
     *
     * @mbg.generated
     */
    private String flightType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.flight_number
     *
     * @mbg.generated
     */
    private String flightNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.flight_date
     *
     * @mbg.generated
     */
    private Date flightDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.operation_detail
     *
     * @mbg.generated
     */
    private String operationDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.attributes
     *
     * @mbg.generated
     */
    private String attributes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.flight_io
     *
     * @mbg.generated
     */
    private String flightIo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.operation_time
     *
     * @mbg.generated
     */
    private Date operationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.operation_type
     *
     * @mbg.generated
     */
    private String operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.operation_id
     *
     * @mbg.generated
     */
    private Long operationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.dept_id
     *
     * @mbg.generated
     */
    private Long deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operation_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.id
     *
     * @return the value of operation_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.id
     *
     * @param id the value for operation_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.flight_type
     *
     * @return the value of operation_log.flight_type
     *
     * @mbg.generated
     */
    public String getFlightType() {
        return flightType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.flight_type
     *
     * @param flightType the value for operation_log.flight_type
     *
     * @mbg.generated
     */
    public void setFlightType(String flightType) {
        this.flightType = flightType == null ? null : flightType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.flight_number
     *
     * @return the value of operation_log.flight_number
     *
     * @mbg.generated
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.flight_number
     *
     * @param flightNumber the value for operation_log.flight_number
     *
     * @mbg.generated
     */
    public void setFlightNumber(String flightNumber) {
        this.flightNumber = flightNumber == null ? null : flightNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.flight_date
     *
     * @return the value of operation_log.flight_date
     *
     * @mbg.generated
     */
    public Date getFlightDate() {
        return flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.flight_date
     *
     * @param flightDate the value for operation_log.flight_date
     *
     * @mbg.generated
     */
    public void setFlightDate(Date flightDate) {
        this.flightDate = flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.operation_detail
     *
     * @return the value of operation_log.operation_detail
     *
     * @mbg.generated
     */
    public String getOperationDetail() {
        return operationDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.operation_detail
     *
     * @param operationDetail the value for operation_log.operation_detail
     *
     * @mbg.generated
     */
    public void setOperationDetail(String operationDetail) {
        this.operationDetail = operationDetail == null ? null : operationDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.attributes
     *
     * @return the value of operation_log.attributes
     *
     * @mbg.generated
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.attributes
     *
     * @param attributes the value for operation_log.attributes
     *
     * @mbg.generated
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes == null ? null : attributes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.flight_io
     *
     * @return the value of operation_log.flight_io
     *
     * @mbg.generated
     */
    public String getFlightIo() {
        return flightIo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.flight_io
     *
     * @param flightIo the value for operation_log.flight_io
     *
     * @mbg.generated
     */
    public void setFlightIo(String flightIo) {
        this.flightIo = flightIo == null ? null : flightIo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.operation_time
     *
     * @return the value of operation_log.operation_time
     *
     * @mbg.generated
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.operation_time
     *
     * @param operationTime the value for operation_log.operation_time
     *
     * @mbg.generated
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.operation_type
     *
     * @return the value of operation_log.operation_type
     *
     * @mbg.generated
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.operation_type
     *
     * @param operationType the value for operation_log.operation_type
     *
     * @mbg.generated
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.operation_id
     *
     * @return the value of operation_log.operation_id
     *
     * @mbg.generated
     */
    public Long getOperationId() {
        return operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.operation_id
     *
     * @param operationId the value for operation_log.operation_id
     *
     * @mbg.generated
     */
    public void setOperationId(Long operationId) {
        this.operationId = operationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.dept_id
     *
     * @return the value of operation_log.dept_id
     *
     * @mbg.generated
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.dept_id
     *
     * @param deptId the value for operation_log.dept_id
     *
     * @mbg.generated
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", flightType=").append(flightType);
        sb.append(", flightNumber=").append(flightNumber);
        sb.append(", flightDate=").append(flightDate);
        sb.append(", operationDetail=").append(operationDetail);
        sb.append(", attributes=").append(attributes);
        sb.append(", flightIo=").append(flightIo);
        sb.append(", operationTime=").append(operationTime);
        sb.append(", operationType=").append(operationType);
        sb.append(", operationId=").append(operationId);
        sb.append(", deptId=").append(deptId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}