package com.chun.quartz.model;

import java.io.Serializable;

public class QrtzFiredTriggers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    private String schedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.ENTRY_ID
     *
     * @mbg.generated
     */
    private String entryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    private String triggerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    private String triggerGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.INSTANCE_NAME
     *
     * @mbg.generated
     */
    private String instanceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.FIRED_TIME
     *
     * @mbg.generated
     */
    private Long firedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.SCHED_TIME
     *
     * @mbg.generated
     */
    private Long schedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.PRIORITY
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.STATE
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.JOB_NAME
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.JOB_GROUP
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @mbg.generated
     */
    private String isNonconcurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @mbg.generated
     */
    private String requestsRecovery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_fired_triggers
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.SCHED_NAME
     *
     * @return the value of qrtz_fired_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.SCHED_NAME
     *
     * @param schedName the value for qrtz_fired_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.ENTRY_ID
     *
     * @return the value of qrtz_fired_triggers.ENTRY_ID
     *
     * @mbg.generated
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.ENTRY_ID
     *
     * @param entryId the value for qrtz_fired_triggers.ENTRY_ID
     *
     * @mbg.generated
     */
    public void setEntryId(String entryId) {
        this.entryId = entryId == null ? null : entryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.TRIGGER_NAME
     *
     * @return the value of qrtz_fired_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.TRIGGER_NAME
     *
     * @param triggerName the value for qrtz_fired_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName == null ? null : triggerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @return the value of qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup == null ? null : triggerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.INSTANCE_NAME
     *
     * @return the value of qrtz_fired_triggers.INSTANCE_NAME
     *
     * @mbg.generated
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.INSTANCE_NAME
     *
     * @param instanceName the value for qrtz_fired_triggers.INSTANCE_NAME
     *
     * @mbg.generated
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName == null ? null : instanceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.FIRED_TIME
     *
     * @return the value of qrtz_fired_triggers.FIRED_TIME
     *
     * @mbg.generated
     */
    public Long getFiredTime() {
        return firedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.FIRED_TIME
     *
     * @param firedTime the value for qrtz_fired_triggers.FIRED_TIME
     *
     * @mbg.generated
     */
    public void setFiredTime(Long firedTime) {
        this.firedTime = firedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.SCHED_TIME
     *
     * @return the value of qrtz_fired_triggers.SCHED_TIME
     *
     * @mbg.generated
     */
    public Long getSchedTime() {
        return schedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.SCHED_TIME
     *
     * @param schedTime the value for qrtz_fired_triggers.SCHED_TIME
     *
     * @mbg.generated
     */
    public void setSchedTime(Long schedTime) {
        this.schedTime = schedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.PRIORITY
     *
     * @return the value of qrtz_fired_triggers.PRIORITY
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.PRIORITY
     *
     * @param priority the value for qrtz_fired_triggers.PRIORITY
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.STATE
     *
     * @return the value of qrtz_fired_triggers.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.STATE
     *
     * @param state the value for qrtz_fired_triggers.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.JOB_NAME
     *
     * @return the value of qrtz_fired_triggers.JOB_NAME
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.JOB_NAME
     *
     * @param jobName the value for qrtz_fired_triggers.JOB_NAME
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.JOB_GROUP
     *
     * @return the value of qrtz_fired_triggers.JOB_GROUP
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.JOB_GROUP
     *
     * @param jobGroup the value for qrtz_fired_triggers.JOB_GROUP
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @return the value of qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @mbg.generated
     */
    public String getIsNonconcurrent() {
        return isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @param isNonconcurrent the value for qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @mbg.generated
     */
    public void setIsNonconcurrent(String isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent == null ? null : isNonconcurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @return the value of qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @mbg.generated
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @mbg.generated
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery == null ? null : requestsRecovery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_fired_triggers
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schedName=").append(schedName);
        sb.append(", entryId=").append(entryId);
        sb.append(", triggerName=").append(triggerName);
        sb.append(", triggerGroup=").append(triggerGroup);
        sb.append(", instanceName=").append(instanceName);
        sb.append(", firedTime=").append(firedTime);
        sb.append(", schedTime=").append(schedTime);
        sb.append(", priority=").append(priority);
        sb.append(", state=").append(state);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", isNonconcurrent=").append(isNonconcurrent);
        sb.append(", requestsRecovery=").append(requestsRecovery);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}