package com.chun.quartz.model;

import java.io.Serializable;

public class QrtzSchedulerState implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @mbg.generated
     */
    private String schedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbg.generated
     */
    private String instanceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbg.generated
     */
    private Long lastCheckinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbg.generated
     */
    private Long checkinInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_scheduler_state
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @return the value of qrtz_scheduler_state.SCHED_NAME
     *
     * @mbg.generated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @param schedName the value for qrtz_scheduler_state.SCHED_NAME
     *
     * @mbg.generated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @return the value of qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbg.generated
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @param instanceName the value for qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbg.generated
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName == null ? null : instanceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @return the value of qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbg.generated
     */
    public Long getLastCheckinTime() {
        return lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @param lastCheckinTime the value for qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbg.generated
     */
    public void setLastCheckinTime(Long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @return the value of qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbg.generated
     */
    public Long getCheckinInterval() {
        return checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @param checkinInterval the value for qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbg.generated
     */
    public void setCheckinInterval(Long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schedName=").append(schedName);
        sb.append(", instanceName=").append(instanceName);
        sb.append(", lastCheckinTime=").append(lastCheckinTime);
        sb.append(", checkinInterval=").append(checkinInterval);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}