package com.chun.quartz.model;

import java.io.Serializable;

public class QrtzTriggers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    private String schedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    private String triggerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    private String triggerGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.JOB_NAME
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.JOB_GROUP
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.NEXT_FIRE_TIME
     *
     * @mbg.generated
     */
    private Long nextFireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.PREV_FIRE_TIME
     *
     * @mbg.generated
     */
    private Long prevFireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.PRIORITY
     *
     * @mbg.generated
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.TRIGGER_STATE
     *
     * @mbg.generated
     */
    private String triggerState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.TRIGGER_TYPE
     *
     * @mbg.generated
     */
    private String triggerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.START_TIME
     *
     * @mbg.generated
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.END_TIME
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.CALENDAR_NAME
     *
     * @mbg.generated
     */
    private String calendarName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.MISFIRE_INSTR
     *
     * @mbg.generated
     */
    private Short misfireInstr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_triggers.JOB_DATA
     *
     * @mbg.generated
     */
    private byte[] jobData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_triggers
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.SCHED_NAME
     *
     * @return the value of qrtz_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.SCHED_NAME
     *
     * @param schedName the value for qrtz_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.TRIGGER_NAME
     *
     * @return the value of qrtz_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.TRIGGER_NAME
     *
     * @param triggerName the value for qrtz_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName == null ? null : triggerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.TRIGGER_GROUP
     *
     * @return the value of qrtz_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup == null ? null : triggerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.JOB_NAME
     *
     * @return the value of qrtz_triggers.JOB_NAME
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.JOB_NAME
     *
     * @param jobName the value for qrtz_triggers.JOB_NAME
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.JOB_GROUP
     *
     * @return the value of qrtz_triggers.JOB_GROUP
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.JOB_GROUP
     *
     * @param jobGroup the value for qrtz_triggers.JOB_GROUP
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.DESCRIPTION
     *
     * @return the value of qrtz_triggers.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.DESCRIPTION
     *
     * @param description the value for qrtz_triggers.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.NEXT_FIRE_TIME
     *
     * @return the value of qrtz_triggers.NEXT_FIRE_TIME
     *
     * @mbg.generated
     */
    public Long getNextFireTime() {
        return nextFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.NEXT_FIRE_TIME
     *
     * @param nextFireTime the value for qrtz_triggers.NEXT_FIRE_TIME
     *
     * @mbg.generated
     */
    public void setNextFireTime(Long nextFireTime) {
        this.nextFireTime = nextFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.PREV_FIRE_TIME
     *
     * @return the value of qrtz_triggers.PREV_FIRE_TIME
     *
     * @mbg.generated
     */
    public Long getPrevFireTime() {
        return prevFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.PREV_FIRE_TIME
     *
     * @param prevFireTime the value for qrtz_triggers.PREV_FIRE_TIME
     *
     * @mbg.generated
     */
    public void setPrevFireTime(Long prevFireTime) {
        this.prevFireTime = prevFireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.PRIORITY
     *
     * @return the value of qrtz_triggers.PRIORITY
     *
     * @mbg.generated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.PRIORITY
     *
     * @param priority the value for qrtz_triggers.PRIORITY
     *
     * @mbg.generated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.TRIGGER_STATE
     *
     * @return the value of qrtz_triggers.TRIGGER_STATE
     *
     * @mbg.generated
     */
    public String getTriggerState() {
        return triggerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.TRIGGER_STATE
     *
     * @param triggerState the value for qrtz_triggers.TRIGGER_STATE
     *
     * @mbg.generated
     */
    public void setTriggerState(String triggerState) {
        this.triggerState = triggerState == null ? null : triggerState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.TRIGGER_TYPE
     *
     * @return the value of qrtz_triggers.TRIGGER_TYPE
     *
     * @mbg.generated
     */
    public String getTriggerType() {
        return triggerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.TRIGGER_TYPE
     *
     * @param triggerType the value for qrtz_triggers.TRIGGER_TYPE
     *
     * @mbg.generated
     */
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType == null ? null : triggerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.START_TIME
     *
     * @return the value of qrtz_triggers.START_TIME
     *
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.START_TIME
     *
     * @param startTime the value for qrtz_triggers.START_TIME
     *
     * @mbg.generated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.END_TIME
     *
     * @return the value of qrtz_triggers.END_TIME
     *
     * @mbg.generated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.END_TIME
     *
     * @param endTime the value for qrtz_triggers.END_TIME
     *
     * @mbg.generated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.CALENDAR_NAME
     *
     * @return the value of qrtz_triggers.CALENDAR_NAME
     *
     * @mbg.generated
     */
    public String getCalendarName() {
        return calendarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.CALENDAR_NAME
     *
     * @param calendarName the value for qrtz_triggers.CALENDAR_NAME
     *
     * @mbg.generated
     */
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName == null ? null : calendarName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.MISFIRE_INSTR
     *
     * @return the value of qrtz_triggers.MISFIRE_INSTR
     *
     * @mbg.generated
     */
    public Short getMisfireInstr() {
        return misfireInstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.MISFIRE_INSTR
     *
     * @param misfireInstr the value for qrtz_triggers.MISFIRE_INSTR
     *
     * @mbg.generated
     */
    public void setMisfireInstr(Short misfireInstr) {
        this.misfireInstr = misfireInstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_triggers.JOB_DATA
     *
     * @return the value of qrtz_triggers.JOB_DATA
     *
     * @mbg.generated
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_triggers.JOB_DATA
     *
     * @param jobData the value for qrtz_triggers.JOB_DATA
     *
     * @mbg.generated
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schedName=").append(schedName);
        sb.append(", triggerName=").append(triggerName);
        sb.append(", triggerGroup=").append(triggerGroup);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", description=").append(description);
        sb.append(", nextFireTime=").append(nextFireTime);
        sb.append(", prevFireTime=").append(prevFireTime);
        sb.append(", priority=").append(priority);
        sb.append(", triggerState=").append(triggerState);
        sb.append(", triggerType=").append(triggerType);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", calendarName=").append(calendarName);
        sb.append(", misfireInstr=").append(misfireInstr);
        sb.append(", jobData=").append(jobData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}