package com.chun.quartz.model;

import java.io.Serializable;

public class QrtzSimpleTriggers implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    private String schedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    private String triggerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    private String triggerGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.REPEAT_COUNT
     *
     * @mbg.generated
     */
    private Long repeatCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @mbg.generated
     */
    private Long repeatInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @mbg.generated
     */
    private Long timesTriggered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_simple_triggers
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.SCHED_NAME
     *
     * @return the value of qrtz_simple_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.SCHED_NAME
     *
     * @param schedName the value for qrtz_simple_triggers.SCHED_NAME
     *
     * @mbg.generated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.TRIGGER_NAME
     *
     * @return the value of qrtz_simple_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.TRIGGER_NAME
     *
     * @param triggerName the value for qrtz_simple_triggers.TRIGGER_NAME
     *
     * @mbg.generated
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName == null ? null : triggerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @return the value of qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_simple_triggers.TRIGGER_GROUP
     *
     * @mbg.generated
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup == null ? null : triggerGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.REPEAT_COUNT
     *
     * @return the value of qrtz_simple_triggers.REPEAT_COUNT
     *
     * @mbg.generated
     */
    public Long getRepeatCount() {
        return repeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.REPEAT_COUNT
     *
     * @param repeatCount the value for qrtz_simple_triggers.REPEAT_COUNT
     *
     * @mbg.generated
     */
    public void setRepeatCount(Long repeatCount) {
        this.repeatCount = repeatCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @return the value of qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @mbg.generated
     */
    public Long getRepeatInterval() {
        return repeatInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @param repeatInterval the value for qrtz_simple_triggers.REPEAT_INTERVAL
     *
     * @mbg.generated
     */
    public void setRepeatInterval(Long repeatInterval) {
        this.repeatInterval = repeatInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @return the value of qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @mbg.generated
     */
    public Long getTimesTriggered() {
        return timesTriggered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @param timesTriggered the value for qrtz_simple_triggers.TIMES_TRIGGERED
     *
     * @mbg.generated
     */
    public void setTimesTriggered(Long timesTriggered) {
        this.timesTriggered = timesTriggered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simple_triggers
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schedName=").append(schedName);
        sb.append(", triggerName=").append(triggerName);
        sb.append(", triggerGroup=").append(triggerGroup);
        sb.append(", repeatCount=").append(repeatCount);
        sb.append(", repeatInterval=").append(repeatInterval);
        sb.append(", timesTriggered=").append(timesTriggered);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}