package com.chun.quartz.model;

import java.io.Serializable;

public class QrtzJobDetails implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.SCHED_NAME
     *
     * @mbg.generated
     */
    private String schedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_NAME
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_GROUP
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbg.generated
     */
    private String jobClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_DURABLE
     *
     * @mbg.generated
     */
    private String isDurable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbg.generated
     */
    private String isNonconcurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbg.generated
     */
    private String isUpdateData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbg.generated
     */
    private String requestsRecovery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_DATA
     *
     * @mbg.generated
     */
    private byte[] jobData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_job_details
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.SCHED_NAME
     *
     * @return the value of qrtz_job_details.SCHED_NAME
     *
     * @mbg.generated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.SCHED_NAME
     *
     * @param schedName the value for qrtz_job_details.SCHED_NAME
     *
     * @mbg.generated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_NAME
     *
     * @return the value of qrtz_job_details.JOB_NAME
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_NAME
     *
     * @param jobName the value for qrtz_job_details.JOB_NAME
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_GROUP
     *
     * @return the value of qrtz_job_details.JOB_GROUP
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_GROUP
     *
     * @param jobGroup the value for qrtz_job_details.JOB_GROUP
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.DESCRIPTION
     *
     * @return the value of qrtz_job_details.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.DESCRIPTION
     *
     * @param description the value for qrtz_job_details.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @return the value of qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbg.generated
     */
    public String getJobClassName() {
        return jobClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @param jobClassName the value for qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbg.generated
     */
    public void setJobClassName(String jobClassName) {
        this.jobClassName = jobClassName == null ? null : jobClassName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_DURABLE
     *
     * @return the value of qrtz_job_details.IS_DURABLE
     *
     * @mbg.generated
     */
    public String getIsDurable() {
        return isDurable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_DURABLE
     *
     * @param isDurable the value for qrtz_job_details.IS_DURABLE
     *
     * @mbg.generated
     */
    public void setIsDurable(String isDurable) {
        this.isDurable = isDurable == null ? null : isDurable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @return the value of qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbg.generated
     */
    public String getIsNonconcurrent() {
        return isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @param isNonconcurrent the value for qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbg.generated
     */
    public void setIsNonconcurrent(String isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent == null ? null : isNonconcurrent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @return the value of qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbg.generated
     */
    public String getIsUpdateData() {
        return isUpdateData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @param isUpdateData the value for qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbg.generated
     */
    public void setIsUpdateData(String isUpdateData) {
        this.isUpdateData = isUpdateData == null ? null : isUpdateData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @return the value of qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbg.generated
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbg.generated
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery == null ? null : requestsRecovery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_DATA
     *
     * @return the value of qrtz_job_details.JOB_DATA
     *
     * @mbg.generated
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_DATA
     *
     * @param jobData the value for qrtz_job_details.JOB_DATA
     *
     * @mbg.generated
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_job_details
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schedName=").append(schedName);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", description=").append(description);
        sb.append(", jobClassName=").append(jobClassName);
        sb.append(", isDurable=").append(isDurable);
        sb.append(", isNonconcurrent=").append(isNonconcurrent);
        sb.append(", isUpdateData=").append(isUpdateData);
        sb.append(", requestsRecovery=").append(requestsRecovery);
        sb.append(", jobData=").append(jobData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}