package com.chun.quartz.model;

import java.io.Serializable;

public class QrtzLocks implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_locks.SCHED_NAME
     *
     * @mbg.generated
     */
    private String schedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_locks.LOCK_NAME
     *
     * @mbg.generated
     */
    private String lockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_locks
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_locks.SCHED_NAME
     *
     * @return the value of qrtz_locks.SCHED_NAME
     *
     * @mbg.generated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_locks.SCHED_NAME
     *
     * @param schedName the value for qrtz_locks.SCHED_NAME
     *
     * @mbg.generated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_locks.LOCK_NAME
     *
     * @return the value of qrtz_locks.LOCK_NAME
     *
     * @mbg.generated
     */
    public String getLockName() {
        return lockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_locks.LOCK_NAME
     *
     * @param lockName the value for qrtz_locks.LOCK_NAME
     *
     * @mbg.generated
     */
    public void setLockName(String lockName) {
        this.lockName = lockName == null ? null : lockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schedName=").append(schedName);
        sb.append(", lockName=").append(lockName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}