package com.chun.quartz.model;

import java.io.Serializable;

public class QrtzCalendars implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.SCHED_NAME
     *
     * @mbg.generated
     */
    private String schedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.CALENDAR_NAME
     *
     * @mbg.generated
     */
    private String calendarName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.CALENDAR
     *
     * @mbg.generated
     */
    private byte[] calendar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qrtz_calendars
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_calendars.SCHED_NAME
     *
     * @return the value of qrtz_calendars.SCHED_NAME
     *
     * @mbg.generated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_calendars.SCHED_NAME
     *
     * @param schedName the value for qrtz_calendars.SCHED_NAME
     *
     * @mbg.generated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_calendars.CALENDAR_NAME
     *
     * @return the value of qrtz_calendars.CALENDAR_NAME
     *
     * @mbg.generated
     */
    public String getCalendarName() {
        return calendarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_calendars.CALENDAR_NAME
     *
     * @param calendarName the value for qrtz_calendars.CALENDAR_NAME
     *
     * @mbg.generated
     */
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName == null ? null : calendarName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_calendars.CALENDAR
     *
     * @return the value of qrtz_calendars.CALENDAR
     *
     * @mbg.generated
     */
    public byte[] getCalendar() {
        return calendar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_calendars.CALENDAR
     *
     * @param calendar the value for qrtz_calendars.CALENDAR
     *
     * @mbg.generated
     */
    public void setCalendar(byte[] calendar) {
        this.calendar = calendar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_calendars
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", schedName=").append(schedName);
        sb.append(", calendarName=").append(calendarName);
        sb.append(", calendar=").append(calendar);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}